# OVERRIDE VALUES IF pr-values:wa tag is applied
servicebus:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-asb
  resourceGroup: probate-aso-preview-rg
  sbNamespace: probate-servicebus-preview
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
        requiresSession: true
global:
  postgresUsername: hmcts
  postgresSecret: postgres
  postgresHost: probate-preview.postgres.database.azure.com
  databaseNamePrefix: "pr-${CHANGE_ID}-"

wa:
  enabled: true
  camunda-bpm:
    java:
      image: hmctsprivate.azurecr.io/camunda/bpm:latest
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_DB_CONN_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"

  wa-case-event-handler:
    java:
      ingressHost: wa-case-event-handler-${SERVICE_FQDN}
      releaseNameOverride: ${SERVICE_NAME}-wa-case-event-handler
      secrets:
        AZURE_SERVICE_BUS_CONNECTION_STRING:
          secretRef: probate-sb-preview
          key: connectionString
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        CCD_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
        CCD_SEARCH_URL: "http://{{ .Release.Name }}-ccd-data-store-api"
        ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
        WA_WORKFLOW_API_URL: "http://{{ .Release.Name }}-wa-workflow-api"
        WA_TASK_MANAGEMENT_API_URL: "http://{{ .Release.Name }}-wa-task-management-api"
        AZURE_SERVICE_BUS_TOPIC_NAME: ${SERVICE_NAME}-ccd-case-events
        AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-ccd-case-events
        AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: ${SERVICE_NAME-ccd-case-events

  wa-task-management-api:
    java:
      ingressHost: wa-task-management-api-${SERVICE_FQDN}
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        CAMUNDA_URL: "http://{{ .Release.Name }}-camunda/engine-rest"
        IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
        ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
        ALLOWED_CASE_TYPES: wacasetype,probate
        ALLOWED_JURISDICTIONS: wa,probate
        MANDATORY_TASK_FIELD_CHECK_ENABLED: true

  wa-task-monitor:
    java:
      ingressHost: wa-task-monitor-${SERVICE_FQDN}
      environment:
        WA_TASK_MANAGEMENT_API_URL: http://{{ .Release.Name }}-wa-task-management-api

  wa-workflow-api:
    java:
      devcpuRequests: 500m
      devmemoryRequests: 1Gi
      devcpuLimits: 2
      devmemoryLimits: 4Gi
      environment:
        DB_READER_USERNAME: "hmcts"

  wa-message-cron-service:
    job:
      schedule: "*/1 * * * *"

  wa-initiation-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-wa-task-batch"

  wa-reconfiguration-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-reconfiguration"

  wa-termination-batch:
    job:
      schedule: "*/1 * * * *"
      releaseNameOverride: "{{ .Release.Name }}-termination-batch"

  #disable wa db as we are using the postgres flexible server
  wa:
    postgresql:
      enabled: false
#check this
am-org-role-mapping-service:
  enabled: true
  java:
    image: 'hmctspublic.azurecr.io/am/org-role-mapping-service:latest'
    ingressHost: am-org-role-mapping-service-${SERVICE_FQDN}
    releaseNameOverride: ${SERVICE_NAME}-am-org-role-mapping-service
    secrets:
      SB_ACCESS_KEY:
        secretRef: probate-sb-preview
        key: primaryKey
      SB_CONNECTION_STRING:
        secretRef: probate-sb-preview
        key: connectionString
      ORG_ROLE_MAPPING_DB_PASSWORD:
        secretRef: "{{ .Values.global.postgresSecret }}"
        key: PASSWORD
        disabled: false
    keyVaults:
      am:
        secrets:
          - name: app-insights-connection-string
            alias: app-insights-connection-string
          - name: am-org-role-mapping-service-s2s-secret
            alias: AM_ORG_ROLE_MAPPING_SERVICE_SECRET
          - name: orm-IDAM-CLIENT-ID
            alias: ORM_IDAM_CLIENT_ID
          - name: orm-IDAM-CLIENT-SECRET
            alias: ORG_ROLE_MAPPING_IDAM_CLIENT_SECRET
          - name: orm-IDAM-ADMIN-SECRET
            alias: ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD
    devcpuRequests: 500m
    devmemoryRequests: 1Gi
    devcpuLimits: 1
    devmemoryLimits: 4Gi
    environment:
      ROLE_ASSIGNMENT_URL: http://${SERVICE_NAME}-am-role-assignment-service
      AMQP_SHARED_ACCESS_KEY_NAME: RootManageSharedAccessKey
      AMQP_HOST: "probate-sb-preview.servicebus.windows.net"
      CRD_SUBSCRIPTION_NAME: "{{ .Release.Name}}-asb-crd-topic"
      JRD_SUBSCRIPTION_NAME: "{{ .Release.Name}}-asb-jrd-topic"
      CRD_TOPIC_NAME: "{{ .Release.Name}}-asb-crd-topic"
      JRD_TOPIC_NAME: "{{ .Release.Name}}-asb-jrd-topic"
      AMQP_CRD_SHARED_ACCESS_KEY_VALUE: "$(SB_ACCESS_KEY)"
      AMQP_JRD_SHARED_ACCESS_KEY_VALUE: "$(SB_ACCESS_KEY)"
      ORG_ROLE_MAPPING_DB_HOST: '{{ tpl .Values.global.postgresHostname $}}'
      ORG_ROLE_MAPPING_DB_NAME: "pr-${CHANGE_ID}-org-role-mapping"
      ORG_ROLE_MAPPING_DB_USERNAME: hmcts
      ORG_ROLE_MAPPING_DB_PORT: 5432
      ORG_ROLE_MAPPING_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      TESTING_SUPPORT_ENABLED: true
      REFRESH_BULK_ASSIGNMENT_INCLUDE_BOOKINGS: true
      DB_FEATURE_FLAG_ENABLE: st_cic_wa_1_0
      ORM_ENV: pr

xui-webapp:
  nodejs:
    environment:
      SERVICES_WA_WORKFLOW_API_URL: http://{{ .Release.Name }}-wa-workflow-api
      HEALTH_WORK_ALLOCATION_TASK_API: http://{{ .Release.Name }}-wa-task-management-api/health
      SERVICES_WORK_ALLOCATION_TASK_API: http://{{ .Release.Name }}-wa-task-management-api
      SERVICES_ROLE_ASSIGNMENT_MAPPING_API: http://{{ .Release.Name }}-am-org-role-mapping-service
      WA_SUPPORTED_JURISDICTIONS: PROBATE

ccd-message-publisher:
  enabled: true
  servicebus:
    enabled: false
  java:
    ingressHost: ccd-message-publisher-${SERVICE_FQDN}
    releaseNameOverride: ${SERVICE_NAME}-ccd-message-publisher
    disableKeyVaults: true # TODO - check if this can be disabled or not
    devcpuRequests: 500m
    devmemoryRequests: 1Gi
    devcpuLimits: 1
    devmemoryLimits: 4Gi
    environment:
      DATA_STORE_DB_HOST: '{{ tpl .Values.global.postgresHost $}}'
      DATA_STORE_DB_NAME: "pr-${CHANGE_ID}-data-store"
      DATA_STORE_DB_USERNAME: hmcts
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      CCD_CASE_EVENTS_DESTINATION: ${SERVICE_NAME}-ccd-case-events
    secrets:
      SERVICE_BUS_CONNECTION_STRING:
        secretRef: probate-sb-preview
        key: connectionString
      DATA_STORE_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: false
