java:
  environment:
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    PDF_SERVICE_URL: http://cmc-pdf-service-aat.service.core-compute-aat.internal
    PRINTSERVICE_HOST: https://return-case-doc-ccd.nonprod.platform.hmcts.net
    PRINTSERVICE_INTERNAL_HOST: http://ccd-case-print-service-aat.service.core-compute-aat.internal
    IDAM_SERVICE_HOST: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    FEE_API_URL: http://fees-register-api-aat.service.core-compute-aat.internal
    EVIDENCE_MANAGEMENT_HOST: http://dm-store-aat.service.core-compute-aat.internal
    CCD_GATEWAY_HOST: http://${SERVICE_NAME}-api-gateway"
#    SERVICES_CORECASEDATA_BASEURL : http://${SERVICE_NAME}-data-store-api
