sol.ccd.service.base.url: ${TEST_URL:http://localhost:4104}
service.auth.provider.base.url: ${SERVICE_AUTH_PROVIDER_BASE_URL:http://localhost:4502}
user.auth.provider.oauth2.url: ${USER_AUTH_PROVIDER_OAUTH2_URL:http://localhost:4501}
evidence.management.url: ${EVIDENCE_MANAGEMENT_URL:http://localhost:8080}
service.name: PROBATE_BACKEND
logging.level.root: DEBUG
idam.oauth2.client.secret: OOOOOOOOOOOOOOOO
idam.oauth2.client.id: ccd_gateway
idam.oauth2.redirect_uri: ${REDIRECT_URL:http://localhost:3451/oauth2redirect}