version: '2.1'

services:
  service-auth-provider-api:
    image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api:47e18b53aad48ae8124744041988565e07dfed50
    container_name: service-auth-provider-api
    environment:
      - AUTH_PROVIDER_SERVICE_SERVER_JWT_KEY=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_PROBATE_BACKEND=CMPRGOBNAUXKYDJL
      - auth.provider.service.server.microserviceKeys.ccd_data=AAAAAAAAAAAAAAAA
      - auth.provider.service.server.microserviceKeys.ccd_ps=AAAAAAAAAAAAAAAA
      - auth.provider.service.server.microserviceKeys.ccd_gw=AAAAAAAAAAAAAAAA
      - auth.provider.service.server.microserviceKeys.ccd_definition=AAAAAAAAAAAAAAAA
      - AUTH_PROVIDER_SERVICE_SERVER_MICROSERVICE_KEYS_EM_GW=AAAAAAAAAAAAAAAA
      - AUTH_PROVIDER_SERVICE_TESTING_SUPPORT_ENABLED=true
    ports:
      - 4502:8080

  pdf-service-api:
    image: docker.artifactory.reform.hmcts.net/cmc/pdf-service-api:latest
    container_name: pdf-service-api
    environment:
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      #volumes:
      #  - ./build/install/pdf-service:/opt/app/
    ports:
      - 5500:5500

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    container_name: idam-api
    command: --wait-for-database 60
    environment:
      - IDAM_SUPERUSER_EMAIL=ccd@hmcts.net
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - SPRING_MAIL_HOST=smtp-server
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - NOTIFY_API_KEY=AAAAAAAAAAAAAAAA
      - NOTIFY_CMC_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
      - IDAM_SECRET=idam_test_secret
      - IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY=OOOOOOOOOOOOOOOO
      - IDAM_CCD_WHITELIST=http://localhost:3451/oauth2redirect
      - NOTIFY=false
      - NOTIFY_CMC_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_SSCS_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_RESET_PASSWORD_TEMPLATE=fake
      - NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_PROBATE_BACKEND_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_CCD_ACTIVATE_USER_TEMPLATE=fake
      - http_proxy
      - https_proxy
      - no_proxy
      # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=idam-api
      - REFORM_TEAM=idam
      - REFORM_ENVIRONMENT=local
    ports:
      - 4501:8080
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest
    container_name: idam-database
    ports:
      - 5430:5432
      #- 5501:5432

  smtp-server:
    container_name: smtp-server
    image: mailhog/mailhog

  document-management-store:
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store:latest
    command: --wait-for-database 30
    environment:
      - SERVER_PORT=8080
      - IDAM_SUPERUSER_EMAIL
      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
      - GOV_NOTIFY_API_KEY
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-management-store-database:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - SPRING_PROFILES_ACTIVE=dev
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_CLIENT_URL=http://idam-api:8080
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - PROVIDER_SERVICE_CLIENT_URL=http://service-auth-provider-api:8080
      - http_proxy=
      - https_proxy=
      - no_proxy=
       # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=document-management-store-app
      - REFORM_TEAM=cc
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=document-management-store-app
      - PACKAGES_VERSION=unknown
#      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 9000:8080
    links:
     - document-management-store-database
     - idam-api
     - service-auth-provider-api
    depends_on:
     - document-management-store-database
     - idam-api
     - service-auth-provider-api

  document-management-store-database:
    build:
      context: ../docker/database
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-database:latest

  document-management-store-api-gateway-web:
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-api-gateway-web:latest
    environment:
      - NODE_ENV=development
      - PORT=8080
      - EM_API_URL=http://document-management-store:8080
      - IDAM_BASE_URL=http://idam-api:8080
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
      - IDAM_SERVICE_NAME=em_gw
      - CORS_ORIGIN_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ORIGIN_WHITELIST=http://document-management-store:8080
      # these environment variables are used by java-logging library
      - ROOT_APPENDER=JSON_CONSOLE
      - LOG_OUTPUT=single
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=node
      - REFORM_SERVICE_NAME=document-management-api-gateway-web
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
  #      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=document-management-api-gateway-web
      - PACKAGES_VERSION=unkown
      - XFWD=true
    ports:
      - 8080:8080
    links:
     - document-management-store
     - idam-api
     - service-auth-provider-api
    depends_on:
     - document-management-store
     - idam-api
     - service-auth-provider-api

  fees-api:
    image: docker.artifactory.reform.hmcts.net/fees-register/fees-api:${FEES_API_DOCKER_VERSION:-latest}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fees-database:5432/fees_register
      - SPRING_DATASOURCE_USERNAME=fees_register
      - SPRING_DATASOURCE_PASSWORD=fees_register
      - AUTH_IDAM_CLIENT_BASEURL=http://idam-api:8080
      - ROOT_APPENDER=JSON_CONSOLE
    ports:
      - 4411:8080
    links:
      - idam-api
      - fees-database
    depends_on:
      - idam-api
      - fees-database

  fees-database:
    image: docker.artifactory.reform.hmcts.net/fees-register/fees-database:${FEES_DATABASE_DOCKER_VERSION:-latest}
    environment:
      - FEES_REGISTER_DB_USERNAME=fees_register
      - FEES_REGISTER_DB_PASSWORD=fees_register

  ccd-user-profile-api:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-api:develop
    container_name: ccd-user-profile-api
    environment:
      - USER_PROFILE_DB_HOST=shared-database
      - USER_PROFILE_DB_PORT=5432
      - USER_PROFILE_DB_USERNAME
      - USER_PROFILE_DB_PASSWORD
      - USER_PROFILE_S2S_AUTHORISED_SERVICES=ccd_data,ccd_definition
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - REFORM_SERVICE_NAME=ccd-user-profile-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
    ports:
      - 4453:4453
    depends_on:
      shared-database:
        condition: service_healthy
    links:
      - ccd-user-profile-database
      - service-auth-provider-api

  ccd-user-profile-database:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-user-profile-database:develop
    container_name: ccd-user-profile-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - USER_PROFILE_DB_USERNAME
      - USER_PROFILE_DB_PASSWORD
    ports:
      - 5453:5432
    volumes:
      - shared-database-data:/var/lib/docker/volumes/solccdservices_shared-database-data/_data

  ccd-definition-store-api:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-api:develop
    container_name: ccd-definition-store-api
    environment:
      - DEFINITION_STORE_DB_HOST=shared-database
      - DEFINITION_STORE_DB_PORT=5432
      - DEFINITION_STORE_DB_USERNAME
      - DEFINITION_STORE_DB_PASSWORD
      - DEFINITION_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
      - DEFINITION_STORE_S2S_AUTHORISED_SERVICES=ccd_data,ccd_gw
      - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
      - IDAM_USER_URL=http://idam-api:8080
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - REFORM_SERVICE_NAME=ccd-definition-store-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
    ports:
      - 4451:4451
    depends_on:
      shared-database:
        condition: service_healthy
    links:
      - ccd-definition-store-database
      - ccd-user-profile-api
      - idam-api
      - service-auth-provider-api

  ccd-definition-store-database:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-definition-store-database:develop
    container_name: ccd-definition-store-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DEFINITION_STORE_DB_USERNAME
      - DEFINITION_STORE_DB_PASSWORD
    ports:
      - 5451:5432
    volumes:
      - shared-database-data:/var/lib/docker/volumes/solccdservices_shared-database-data/_data

  ccd-data-store-api:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-api:develop
    container_name: ccd-data-store-api
    environment:
      - DATA_STORE_DB_HOST=shared-database
      - DATA_STORE_DB_PORT=5432
      - DATA_STORE_DB_USERNAME
      - DATA_STORE_DB_PASSWORD
      - DATA_STORE_IDAM_KEY=AAAAAAAAAAAAAAAA
      - DATA_STORE_TOKEN_SECRET=iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      - DATA_STORE_S2S_AUTHORISED_SERVICES=ccd_gw,ccd_data,ccd_ps,probate_backend
      - DEFINITION_STORE_HOST=http://ccd-definition-store-api:4451
      - USER_PROFILE_HOST=http://ccd-user-profile-api:4453
      - IDAM_USER_URL=http://idam-api:8080
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - REFORM_SERVICE_NAME=ccd-data-store-api
      - REFORM_TEAM=ccd
      - REFORM_ENVIRONMENT=local
      - CCD_DM_DOMAIN=http://localhost:8080
      - CCD_DEFAULTPRINTURL=http://localhost:3100/jurisdictions/:jid/case-types/:ctid/cases/:cid
    ports:
      - 4452:4452
    depends_on:
      shared-database:
        condition: service_healthy
    links:
      - ccd-data-store-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - idam-api
      - service-auth-provider-api

  ccd-data-store-database:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-data-store-database:develop
    container_name: ccd-data-store-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - DATA_STORE_DB_USERNAME
      - DATA_STORE_DB_PASSWORD
    ports:
      - 5452:5432
    volumes:
      - shared-database-data:/var/lib/docker/volumes/solccdservices_shared-database-data/_data

  shared-database:
    image: postgres:9.6-alpine
    container_name: shared-database
    ports:
      - 5342:5432
    healthcheck:
      test: psql -c 'select 1' -d postgres -U postgres
      retries: 2
    mem_limit: 160m
    memswap_limit: 0
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  authentication-web:
    image: docker.artifactory.reform.hmcts.net/auth/authentication-web:latest
    container_name: authentication-web
    environment:
     - IDAM_API_URL=http://idam-api:8080
     - IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS=false
    ports:
     - 8000:8000
    links:
     - idam-api
    depends_on:
     - idam-api

  ccd-case-management-web:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-case-management-web:develop
    container_name: ccd-case-management-web
    environment:
      - IDAM_LOGIN_URL=https://localhost:8000/login
      - CCD_GATEWAY_BASE_URL=http://localhost:3453
      - CCD_ACTIVITY_BASE_URL=
      - DM_GATEWAY_BASE_URL=https://api-gateway.dev.dm.reform.hmcts.net
      - OAUTH2_CLIENT_ID=ccd_gateway
      - DOCUMENT_MANAGEMENT_URL=http://localhost:3453/documents
      - REMOTE_DOCUMENT_MANAGEMENT_URL=http://localhost:8080/documents
    ports:
      - 3451:80

  ccd-api-gateway:
    image: docker.artifactory.reform.hmcts.net/ccd/ccd-api-gateway:develop
    container_name: ccd-api-gateway
    environment:
      - IDAM_BASE_URL=http://idam-api:8080
      - IDAM_USER_URL=http://idam-api:8080
      - IDAM_S2S_URL=http://service-auth-provider-api:8080
      - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
      - IDAM_SERVICE_NAME=ccd_gw
      - LOGOUT_URL=https://localhost:3501/login/logout
      - IDAM_OAUTH2_TOKEN_ENDPOINT=http://idam-api:8080/oauth2/token
      - IDAM_OAUTH2_CLIENT_ID=ccd_gateway
      - IDAM_OAUTH2_CLIENT_SECRET=OOOOOOOOOOOOOOOO
      - PROXY_AGGREGATED=http://ccd-data-store-api:4452
      - PROXY_DATA=http://ccd-data-store-api:4452
      - PROXY_DEFINITION_IMPORT=http://ccd-definition-store-api:4451
      - PROXY_DEFINITION_DATA=http://ccd-definition-store-api:4451/api/data
      - PROXY_DEFINITION_DISPLAY=http://ccd-definition-store-api:4451/api/display
      # this NEEDS to be your local ip address
      - PROXY_PRINT_SERVICE=http://172.16.1.15:3100
      - PROXY_DOCUMENT_MANAGEMENT=http://document-management-store-api-gateway-web:8080
    ports:
      - 3453:3453

volumes:
  shared-database-data:
